# .github/workflows/license-audit.yml
name: License Audit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run License Audit
        run: |
          vendor/bin/license-audit --fail-on-blacklist --csv=report/licenses.csv

      - name: Run Tests
        run: vendor/bin/phpunit --display-deprecations

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: report/licenses.csv
